name: Verify Loom
on: [push, pull_request]
permissions:
  contents: read
jobs:
  documentation:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: sudo apt-get update && sudo apt-get install -y g++-12 lcov clang-format-14 clang-tidy-14
      - run: make check
        env:
          CXX: g++-12
          GCOV: gcov-12
